name: kicks_connect
description: Multi-platform shoe store (web, Android, iOS) built with Flutter.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  go_router: any
  flutter_riverpod: any
  intl: any
  cached_network_image: any
  # Firebase (optional until configured)
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  # Payments (implement one or more providers in app/services/payment)
  flutter_stripe: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
